version: '3'

services:

  app:
    restart: always
    build:
       context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - network
    expose:
      - "6379"
    ports:
      - "6379:6379"

  celery:
    restart: always
    build:
      context: .
    command: celery -A src worker -B -l INFO
    env_file:
      - .env
    depends_on:
      - app
      - redis
    networks:
      - network

networks:
  network:

