# Generated by Django 3.1.3 on 2020-12-05 21:53

import uuid

import colorfield.fields
import django.db.models.deletion
import sort_order_field.fields
import tinymce.models
from django.conf import settings
from django.db import migrations, models

import src.mextalki.models.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('button_text', models.CharField(default='', max_length=50)),
                ('button_link', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to=src.mextalki.models.utils.upload_image_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('slug', models.SlugField(default='')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('home_description', models.TextField(default='')),
                (
                    'thumbnail', models.ImageField(
                        default='',
                        upload_to=src.mextalki.models.utils.upload_thumbnail_to,
                    ),
                ),
                ('video', models.URLField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                (
                    'learn_description', tinymce.models.HTMLField(
                        blank=True, default='', null=True,
                    ),
                ),
                (
                    'grid_description', models.TextField(
                        blank=True, max_length=500, null=True,
                    ),
                ),
                (
                    'course_extend_description', tinymce.models.HTMLField(
                        blank=True, default='', null=True,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('white_font', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='')),
                ('title', models.CharField(max_length=255)),
                ('link_title', models.CharField(max_length=50)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('content_description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('free', models.BooleanField(default=False)),
                (
                    'type', models.CharField(
                        choices=[
                            ('LESSON', 'LESSON'), ('MODULE', 'MODULE'),
                        ], max_length=20,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListeningPractice',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'description', tinymce.models.HTMLField(
                        blank=True, default='', null=True,
                    ),
                ),
                (
                    'lesson', models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='listening_practice', to='mextalki.lesson',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Lessons - Listening Practices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id', models.UUIDField(
                        default=uuid.uuid4,
                        editable=False, primary_key=True, serialize=False,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                (
                    'description', tinymce.models.HTMLField(
                        blank=True, default='', null=True,
                    ),
                ),
                ('price', models.FloatField()),
                (
                    'currency', models.CharField(
                        choices=[
                            ('USD', 'USD'), ('MXN', 'MXN'),
                        ], default='USD', max_length=3,
                    ),
                ),
                ('active', models.BooleanField(default=True)),
                (
                    'course', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='plans', to='mextalki.course',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeakingPractice',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                (
                    'lesson', models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='speaking_practice', to='mextalki.lesson',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Lessons - Speaking Practices',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                (
                    'thumbnail', models.ImageField(
                        default='',
                        upload_to=src.mextalki.models.utils.upload_thumbnail_to,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsefulSpanish',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'lesson', models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='useful_spanish', to='mextalki.lesson',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Lessons - Useful Spanish',
            },
        ),
        migrations.CreateModel(
            name='UsefulSpanishAudio',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to=src.mextalki.models.utils.upload_file_to)),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0)),
                (
                    'useful_spanish', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audio_resources', to='mextalki.usefulspanish',
                    ),
                ),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='SpeakingPracticeResource',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=50)),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0)),
                (
                    'speaking_practice', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='resources', to='mextalki.speakingpractice',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeakingPracticeAudio',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                (
                    'description', tinymce.models.HTMLField(
                        blank=True, default='', null=True,
                    ),
                ),
                ('file', models.FileField(upload_to=src.mextalki.models.utils.upload_file_to)),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0)),
                (
                    'speaking_practice', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audio_resources', to='mextalki.speakingpractice',
                    ),
                ),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='PlanBoxItem',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                (
                    'course', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='plan_list', to='mextalki.course',
                    ),
                ),
                (
                    'plan', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='mextalki.plan',
                    ),
                ),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='PaypalPayment',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                (
                    'intent', models.CharField(
                        choices=[
                            ('CAPTURE', 'CAPTURE'), ('AUTHORIZE', 'AUTHORIZE'),
                        ], max_length=10,
                    ),
                ),
                (
                    'status', models.CharField(
                        choices=[
                            ('CREATED', 'CREATED'), ('SAVED', 'SAVED'), ('APPROVED', 'APPROVED'), (
                                'VOIDED', 'VOIDED',
                            ), ('COMPLETED', 'COMPLETED'), ('PAYER_ACTION_REQUIRED', 'PAYER_ACTION_REQUIRED'),
                        ], max_length=50,
                    ),
                ),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('payer_email', models.EmailField(max_length=254)),
                ('payer_id', models.CharField(max_length=20)),
                ('payer_name', models.CharField(max_length=300)),
                (
                    'payment', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='paypal_payment', to='mextalki.payment',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='mextalki.plan',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payments', to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('spanish_transcription', tinymce.models.HTMLField(blank=True, null=True)),
                ('english_transcription', tinymce.models.HTMLField(blank=True, null=True)),
                (
                    'lesson', models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='module_info', to='mextalki.lesson',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Modules - Module Info',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                (
                    'course', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='modules', to='mextalki.course',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListeningPracticeAudio',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('transcription', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', tinymce.models.HTMLField()),
                ('file', models.FileField(upload_to=src.mextalki.models.utils.upload_file_to)),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0)),
                (
                    'listening_practice', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audio_resources', to='mextalki.listeningpractice',
                    ),
                ),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0)),
                (
                    'lesson', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='videos', to='mextalki.lesson',
                    ),
                ),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='lessons', to='mextalki.module',
            ),
        ),
        migrations.CreateModel(
            name='CourseGridPic',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0)),
                ('label', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=src.mextalki.models.utils.upload_image_to)),
                ('big_size', models.BooleanField(default=False)),
                (
                    'course', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='grid_pics', to='mextalki.course',
                    ),
                ),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='ContentListItem',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('label', models.CharField(max_length=100)),
                (
                    'course', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='content_list', to='mextalki.course',
                    ),
                ),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
    ]
