# Generated by Django 3.1.4 on 2020-12-26 20:56

import uuid

import colorfield.fields
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mextalki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id', models.UUIDField(
                        default=uuid.uuid4,
                        editable=False, primary_key=True, serialize=False,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                (
                    'status', models.CharField(
                        choices=[
                            ('CREATED', 'CREATED'), ('APPROVAL_PENDING', 'APPROVAL PENDING'), ('APPROVED', 'APPROVED'), (
                                'ACTIVE', 'ACTIVE',
                            ), ('SUSPENDED', 'SUSPENDED'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED'),
                        ], default='CREATED', max_length=24,
                    ),
                ),
                ('next_billing_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                (
                    'description', tinymce.models.HTMLField(
                        blank=True, default='', null=True,
                    ),
                ),
                ('price', models.FloatField()),
                (
                    'currency', models.CharField(
                        choices=[
                            ('USD', 'USD'), ('MXN', 'MXN'),
                        ], default='USD', max_length=3,
                    ),
                ),
                ('active', models.BooleanField(default=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                (
                    'billing_cycle', models.CharField(
                        choices=[
                            ('WEEK', 'WEEKLY'), ('MONTH', 'MONTHLY'), ('YEAR', 'YEARLY'),
                        ], default='MONTH', max_length=10,
                    ),
                ),
                ('paypal_plan_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ('price',),
            },
        ),
        migrations.RemoveField(
            model_name='paypalpayment',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mextalki.subscriptiontype',
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='subscriptions', to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='planpayment',
            name='paypal_payment',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='mextalki.paypalpayment',
            ),
        ),
        migrations.AddField(
            model_name='planpayment',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='mextalki.plan',
            ),
        ),
        migrations.AddField(
            model_name='planpayment',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payments', to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
