# Generated by Django 3.1.4 on 2020-12-27 03:37

import tinymce.models
from django.db import migrations, models

import src.mextalki.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0002_auto_20201226_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'description', tinymce.models.HTMLField(
                        blank=True, default='', null=True,
                    ),
                ),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=src.mextalki.models.utils.upload_image_to)),
                ('thirty_min_calendar_url', models.CharField(max_length=255)),
                ('sixty_min_calendar_url', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
