# Generated by Django 3.1.4 on 2020-12-28 17:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='provider',
            field=models.CharField(
                choices=[('PAYPAL', 'PAYPAL'), ('STRIPE', 'STRIPE')], default='', max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='provider_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False,
                primary_key=True, serialize=False,
            ),
        ),
    ]
