# Generated by Django 3.1.4 on 2020-12-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0004_auto_20201228_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=20)),
                ('charge_id', models.CharField(max_length=20)),
                ('billing_reason', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_intent', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('subscription_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
