# Generated by Django 3.1.4 on 2020-12-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0006_auto_20201231_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='lesson',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link_title',
            field=models.CharField(max_length=255),
        ),
    ]
