# Generated by Django 3.1.4 on 2021-01-07 03:53

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0007_auto_20201231_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingpractice',
            name='bottom_message',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speakingpractice',
            name='section_title',
            field=models.CharField(
                choices=[
                    ('Speaking Practice', 'Speaking Practice'), (
                        'Exercises', 'Exercises',
                    ),
                ], default='Speaking Practice', max_length=50,
            ),
        ),
    ]
