# Generated by Django 3.1.5 on 2021-01-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0008_auto_20210106_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='presentation_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
