# Generated by Django 3.1.5 on 2021-01-21 16:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mextalki', '0009_teacher_presentation_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('active', models.BooleanField(default=True)),
                (
                    'event_duration', models.IntegerField(
                        default=0, help_text='Set in minutes',
                    ),
                ),
                ('calendar_url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Scheduled events - Types',
            },
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='sixty_min_calendar_url',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='thirty_min_calendar_url',
        ),
        migrations.AddField(
            model_name='subscription',
            name='available_lesson_time',
            field=models.IntegerField(default=0, help_text='Set in minutes'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='lesson_time',
            field=models.IntegerField(default=0, help_text='Set in hours'),
        ),
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id', models.UUIDField(
                        default=uuid.uuid4,
                        editable=False, primary_key=True, serialize=False,
                    ),
                ),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                (
                    'provider', models.CharField(
                        blank=True, choices=[
                            ('CALENDLY', 'CALENDLY'),
                        ], max_length=10, null=True,
                    ),
                ),
                ('provider_id', models.CharField(max_length=50, null=True)),
                (
                    'status', models.CharField(
                        choices=[
                            ('ACTIVE', 'ACTIVE'), ('CANCELLED', 'CANCELLED'), (
                                'RESCHEDULED', 'RESCHEDULED',
                            ),
                        ], default='ACTIVE', max_length=24,
                    ),
                ),
                (
                    'event_type', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='mextalki.eventtype',
                    ),
                ),
                (
                    'teacher', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='teacher_scheduled_events', to='mextalki.teacher',
                    ),
                ),
                (
                    'user', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='user_scheduled_events', to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='eventtype',
            name='teacher',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='event_types', to='mextalki.teacher',
            ),
        ),
    ]
