# Generated by Django 3.1.5 on 2021-01-27 06:27

import colorfield.fields
import django.db.models.deletion
import sort_order_field.fields
from django.db import migrations, models

import src.mextalki.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0010_auto_20210121_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=src.mextalki.models.utils.upload_image_to)),
                ('slug', models.SlugField(default='')),
                ('video', models.URLField(blank=True, null=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('white_font', models.BooleanField(default=False)),
                ('link_title', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('free', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='provider_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PodcastCaption',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'src_language', models.CharField(
                        choices=[
                            ('EN', 'ENGLISH'), ('SV', 'SWEDISH'), ('ES', 'SPANISH'),
                        ], max_length=10,
                    ),
                ),
                ('file', models.FileField(upload_to=src.mextalki.models.utils.upload_file_to)),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0)),
                (
                    'podcast', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='captions', to='mextalki.podcast',
                    ),
                ),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
    ]
