# Generated by Django 3.1.5 on 2021-02-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0011_auto_20210127_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningpracticeaudio',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
