# Generated by Django 3.1.5 on 2021-02-10 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201111_2228'),
        ('mextalki', '0012_auto_20210209_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvailableLessonTime',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user', models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                        related_name='user_available_lesson_time', serialize=False, to='users.user',
                    ),
                ),
                ('time', models.IntegerField(default=0, help_text='Set in minutes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
