# Generated by Django 3.1.5 on 2021-02-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0013_useravailablelessontime'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='extra_hour_currency',
            field=models.CharField(
                choices=[('USD', 'USD'), ('MXN', 'MXN')], default='USD', max_length=3,
            ),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='extra_hour_price',
            field=models.FloatField(default=0, help_text='Lesson extra Hour price'),
        ),
    ]
