# Generated by Django 3.1.6 on 2021-02-24 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0015_auto_20210221_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastcaption',
            name='podcast',
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
        migrations.DeleteModel(
            name='PodcastCaption',
        ),
    ]
