# Generated by Django 3.1.7 on 2021-03-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0018_auto_20210306_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
