# Generated by Django 3.1.7 on 2021-04-05 21:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0019_testimonial_testimonial_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
