# Generated by Django 3.1.7 on 2021-04-07 03:16

import tinymce.models
from django.db import migrations, models

import src.mextalki.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0020_auto_20210405_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCopyInfo',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('text', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('icon', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=src.mextalki.models.utils.upload_image_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainCopy',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
