# Generated by Django 3.2 on 2021-04-09 15:04

import django.db.models.deletion
import timezone_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mextalki', '0021_homecopyinfo_maincopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='America/Mexico_City'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='America/Mexico_City'),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_scheduled_events', to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
