# Generated by Django 3.2 on 2021-04-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0023_auto_20210415_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecopyinfo',
            options={'verbose_name_plural': 'What we offer - Sections'},
        ),
        migrations.AlterModelOptions(
            name='maincopy',
            options={'verbose_name_plural': 'Your mexican spanish hub - Sections'},
        ),
        migrations.AddField(
            model_name='homecopyinfo',
            name='button_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homecopyinfo',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maincopy',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
