# Generated by Django 3.2 on 2021-05-02 05:00

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models

import src.mextalki.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0024_auto_20210424_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationClubInfo',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('club_info', tinymce.models.HTMLField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationClubTestimonial',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                (
                    'thumbnail', models.ImageField(
                        upload_to=src.mextalki.models.utils.upload_thumbnail_to,
                    ),
                ),
                (
                    'flag_thumbnail', models.ImageField(
                        upload_to=src.mextalki.models.utils.upload_thumbnail_to,
                    ),
                ),
                ('testimonial_video_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='maincopy',
            options={
                'ordering': (
                    'id',
                ), 'verbose_name_plural': 'Your mexican spanish hub - Sections',
            },
        ),
        migrations.CreateModel(
            name='ConversationClubSchedule',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(max_length=255)),
                ('hour', models.TimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                (
                    'copy', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='schedules_list', to='mextalki.conversationclubinfo',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
