# Generated by Django 3.2 on 2021-05-08 15:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0025_auto_20210502_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.CharField(max_length=255)),
                ('youtube_video_id', models.CharField(max_length=255)),
                (
                    'blog_content', tinymce.models.HTMLField(
                        blank=True, default='', null=True,
                    ),
                ),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='conversationclubschedule',
            name='day',
            field=models.CharField(
                choices=[
                    ('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), (
                        '4', 'Thursday',
                    ), ('5', 'Friday'), ('6', 'Saturday'),
                ], default='0', max_length=255,
            ),
        ),
    ]
