# Generated by Django 3.2 on 2021-05-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0026_auto_20210508_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiontype',
            old_name='extra_hour_price',
            new_name='extra_hour_lesson_price',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='is_conversation_club',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='available_lesson_time',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='type',
            field=models.CharField(
                choices=[
                    (
                        '1', 'LESSON',
                    ), ('2', 'PRACTICE'), ('3', 'CONVERSATION_CLUB'),
                ], default='1', max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='extra_hour_practice_price',
            field=models.FloatField(default=0, help_text='Practice extra Hour price'),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='practice_time',
            field=models.IntegerField(default=0, help_text='Set in hours'),
        ),
        migrations.AddField(
            model_name='useravailablelessontime',
            name='practice_time',
            field=models.IntegerField(default=0, help_text='Set in minutes'),
        ),
    ]
