# Generated by Django 3.2.4 on 2021-06-16 05:03

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0029_answer_lessontest_question_testscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', tinymce.models.HTMLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                (
                    'faq', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='questions', to='mextalki.faq',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
