# Generated by Django 3.2.4 on 2021-06-22 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
        ('mextalki', '0030_faq_faqquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExperiencePoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user', models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                        related_name='user_experience_points', serialize=False, to='users.user',
                    ),
                ),
                ('scheduled_event_exp_points', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
