# Generated by Django 3.2.4 on 2021-07-16 03:01

import django.db.models.deletion
import sort_order_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0031_userexperiencepoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationclubtestimonial',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='conversationclubtestimonial',
            name='copy',
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='testimonials_list', to='mextalki.conversationclubinfo',
            ),
        ),
        migrations.AddField(
            model_name='conversationclubtestimonial',
            name='sort_order',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='conversationclubschedule',
            name='copy',
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='schedules_list', to='mextalki.conversationclubinfo',
            ),
        ),
    ]
