# Generated by Django 3.2.4 on 2021-07-21 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mextalki', '0032_auto_20210715_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastTest',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                (
                    'podcast', models.ForeignKey(
                        blank=True, default=None, null=True,
                        on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='mextalki.podcast',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Podcast - Tests',
            },
        ),
        migrations.CreateModel(
            name='PodcastTestScore',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('attempt_counter', models.PositiveIntegerField(default=0)),
                ('full_well_answered', models.BooleanField(default=False)),
                ('correct_answered', models.PositiveIntegerField(default=0)),
                ('exp_points', models.FloatField(default=0)),
                (
                    'test', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='scores', to='mextalki.podcasttest',
                    ),
                ),
                (
                    'user', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='podcast_tests_scores', to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PodcastTestQuestion',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                (
                    'test', models.ForeignKey(
                        blank=True, default=None, null=True,
                        on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='mextalki.podcasttest',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PodcastTestAnswer',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(max_length=255)),
                ('correct_answer', models.BooleanField(default=False)),
                (
                    'question', models.ForeignKey(
                        blank=True, default=None, null=True,
                        on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='mextalki.podcasttestquestion',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
