# Generated by Django 3.2.6 on 2021-08-30 04:27

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models

import src.mextalki.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0034_auto_20210807_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskCopy',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('how_get_points', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaskInfo',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('info', tinymce.models.HTMLField(blank=True, null=True)),
                (
                    'mask_image', models.ImageField(
                        upload_to=src.mextalki.models.utils.upload_to_v2,
                    ),
                ),
                ('active', models.BooleanField(default=True)),
                (
                    'mask_copy', models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='mextalki.maskcopy',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
