# Generated by Django 3.2.7 on 2021-09-29 05:13

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('mextalki', '0036_coupon_usedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='podcast',
            name='tags',
            field=taggit.managers.TaggableManager(
                blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags',
            ),
        ),
    ]
