# Generated by Django 3.2.7 on 2021-10-07 04:24

import django.db.models.deletion
from django.db import migrations, models

import src.mextalki.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0037_auto_20210929_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersReview',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('review', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                (
                    'thumbnail', models.ImageField(
                        default='',
                        upload_to=src.mextalki.models.utils.upload_to_v2,
                    ),
                ),
                (
                    'teacher', models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mextalki.teacher',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
