# Generated by Django 3.2.7 on 2021-10-13 03:28

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0038_teachersreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_for_limited_time',
            field=models.BooleanField(
                default=False, verbose_name='Is for limited time and can be unlimited times used by user',
            ),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limited_time',
            field=models.DateField(
                default=datetime.datetime(
                    2021, 10, 13, 3, 28, 6, 814991, tzinfo=utc,
                ),
            ),
        ),
    ]
