# Generated by Django 3.2.7 on 2021-10-18 02:42

import datetime

import sort_order_field.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0039_auto_20211012_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='sort_order',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='limited_time',
            field=models.DateField(
                default=datetime.datetime(
                    2021, 10, 18, 2, 42, 27, 22673, tzinfo=utc,
                ),
            ),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='sort_order',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0),
        ),
    ]
