# Generated by Django 3.2.7 on 2021-10-18 03:18

import datetime

import django.db.models.deletion
import sort_order_field.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0040_auto_20211017_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('sort_order',)},
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='limited_time',
            field=models.DateField(
                default=datetime.datetime(
                    2021, 10, 18, 3, 18, 6, 44150, tzinfo=utc,
                ),
            ),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('sort_order', sort_order_field.fields.SortOrderField(db_index=True, default=0)),
                (
                    'course', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='levels', to='mextalki.course',
                    ),
                ),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='module',
            name='level',
            field=models.ForeignKey(
                blank=True, default=None, null=True,
                on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='mextalki.level',
            ),
        ),
    ]
