# Generated by Django 3.2.7 on 2021-10-26 04:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0041_auto_20211017_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={
                'ordering': ('sort_order',), 'verbose_name': 'Course - Lesson',
                'verbose_name_plural': 'Courses - Lessons',
            },
        ),
        migrations.AlterModelOptions(
            name='level',
            options={
                'ordering': ('sort_order',), 'verbose_name': 'Course - Level',
                'verbose_name_plural': 'Courses - Levels',
            },
        ),
        migrations.AlterModelOptions(
            name='module',
            options={
                'ordering': ('sort_order',), 'verbose_name': 'Course - Modules',
                'verbose_name_plural': 'Courses - Modules',
            },
        ),
        migrations.RenameField(
            model_name='useravailablelessontime',
            old_name='time',
            new_name='lesson_time',
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='scheduled_with_purchased_time',
            field=models.IntegerField(default=0, help_text='Set in minutes'),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='scheduled_with_subscription_time',
            field=models.IntegerField(default=0, help_text='Set in minutes'),
        ),
        migrations.AddField(
            model_name='useravailablelessontime',
            name='purchased_lesson_time',
            field=models.IntegerField(default=0, help_text='Set in minutes'),
        ),
        migrations.AddField(
            model_name='useravailablelessontime',
            name='purchased_practice_time',
            field=models.IntegerField(default=0, help_text='Set in minutes'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='limited_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
