# Generated by Django 3.2.7 on 2021-10-30 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0043_leadershipscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipscore',
            name='created_at',
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True,
            ),
        ),
    ]
