# Generated by Django 3.2.7 on 2021-10-30 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mextalki', '0044_alter_leadershipscore_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipscore',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='leadership_board_scores', to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
