# Generated by Django 3.2.7 on 2021-11-18 00:32

from django.db import migrations, models

import src.mextalki.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0046_leadershipboardinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='captions',
            field=models.FileField(
                blank=True, default=None, null=True,
                upload_to=src.mextalki.models.utils.upload_to_v2,
            ),
        ),
    ]
