# Generated by Django 3.2.9 on 2021-11-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0047_podcast_captions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='include_podcast_features',
            field=models.BooleanField(default=False),
        ),
    ]
