# Generated by Django 3.2.9 on 2021-12-03 22:28

from django.db import migrations, models

import src.mextalki.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0048_subscriptiontype_include_podcast_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='mp3_file',
            field=models.FileField(
                blank=True, default=None, null=True,
                upload_to=src.mextalki.models.utils.upload_to_v2,
            ),
        ),
    ]
