# Generated by Django 3.2.9 on 2022-01-13 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mextalki', '0049_podcast_mp3_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoScore',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exp_points', models.IntegerField(default=0)),
                ('user_already_get_points', models.BooleanField(default=False)),
                (
                    'podcast', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='video_scores', to='mextalki.podcast',
                    ),
                ),
                (
                    'user', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='video_scores', to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
