# Generated by Django 3.2.9 on 2022-01-26 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0051_commonvideoscore_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonvideoscore',
            options={'verbose_name_plural': 'Scores - Videos'},
        ),
        migrations.AlterModelOptions(
            name='videoscore',
            options={'verbose_name_plural': 'Scores - Podcast'},
        ),
    ]
