# Generated by Django 3.2.11 on 2022-02-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0055_auto_20220205_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='earned_credits',
            field=models.IntegerField(default=0),
        ),
    ]
