# Generated by Django 3.2.11 on 2022-02-09 21:52

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0056_referral_earned_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoardRewards',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('how_get_points', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Leaderboard Rewards',
            },
        ),
        migrations.AddField(
            model_name='leadershipscore',
            name='lesson_time_exp_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadershipscore',
            name='tests_exp_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadershipscore',
            name='videos_exp_points',
            field=models.IntegerField(default=0),
        ),
    ]
