# Generated by Django 3.2.11 on 2022-02-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0057_auto_20220209_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationclubinfo',
            name='video_example_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
