# Generated by Django 3.2.11 on 2022-03-31 02:34

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models

import src.mextalki.models.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mextalki', '0058_conversationclubinfo_video_example_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'created_at', models.DateField(
                        blank=True,
                        default=django.utils.timezone.now, null=True,
                    ),
                ),
                ('title', models.CharField(max_length=125)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                (
                    'image', models.ImageField(
                        default='',
                        upload_to=src.mextalki.models.utils.upload_to_v2,
                    ),
                ),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name_plural': 'Forum - Announcements',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'content_type', models.CharField(
                        choices=[
                            ('AN', 'Announcement'),
                        ], default='AN', max_length=2,
                    ),
                ),
                ('active', models.BooleanField(default=True)),
                (
                    'announcement', models.OneToOneField(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE, related_name='post', to='mextalki.announcement',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                (
                    'post', models.ForeignKey(
                        blank=True, default=None, null=True,
                        on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='mextalki.post',
                    ),
                ),
                (
                    'user', models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                        related_name='likes', to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
