# Generated by Django 3.2.11 on 2022-04-06 19:53

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models

import src.mextalki.models.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mextalki', '0059_announcement_like_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'created_at', models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now, null=True,
                    ),
                ),
                ('title', models.CharField(max_length=125)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name_plural': 'Forum - Challenges',
            },
        ),
        migrations.AddField(
            model_name='leadershipscore',
            name='challenges_exp_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True,
            ),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(
                blank=True, default='', null=True,
                upload_to=src.mextalki.models.utils.upload_to_v2,
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(
                choices=[('AN', 'Announcement'), ('CH', 'Challenge')], default='AN', max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('is_challenge_correct_answer', models.BooleanField(default=False)),
                (
                    'post', models.ForeignKey(
                        default=None, on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments', to='mextalki.post',
                    ),
                ),
                (
                    'user', models.ForeignKey(
                        default=None, on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments', to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='challenge',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='mextalki.challenge',
            ),
        ),
    ]
