# Generated by Django 3.2.11 on 2022-04-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0060_auto_20220406_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravailablelessontime',
            name='purchased_conversation_club_slots',
            field=models.IntegerField(default=0, help_text='set club access slots'),
        ),
    ]
