# Generated by Django 3.2.13 on 2022-05-09 01:40

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models

import src.mextalki.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0062_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningpracticeaudio',
            name='transcription',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='LessonActivity',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='', null=True,
                 upload_to=src.mextalki.models.utils.upload_to_v2)),
                ('activity_description', tinymce.models.HTMLField(
                    blank=True, default='', null=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='activity', to='mextalki.lesson')),
            ],
            options={
                'verbose_name_plural': 'Lessons - Activities',
            },
        ),
    ]
