# Generated by Django 3.2.13 on 2022-05-20 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mextalki', '0063_auto_20220508_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_payments_old', to=settings.AUTH_USER_MODEL),
        ),
    ]
