# Generated by Django 3.2.13 on 2022-06-24 17:23

from django.db import migrations, models
import django.db.models.deletion
import src.mextalki.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0064_alter_planpayment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonactivity',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageLessonActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='', upload_to=src.mextalki.models.utils.upload_to_v2)),
                ('lesson_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mextalki.lessonactivity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
