# Generated by Django 3.2.14 on 2022-08-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0065_auto_20220624_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Forum - Comments'},
        ),
    ]
