# Generated by Django 3.2.16 on 2022-10-13 01:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.mextalki.models.utils
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mextalki', '0068_auto_20221012_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('title', models.CharField(max_length=125)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('preview', tinymce.models.HTMLField()),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=src.mextalki.models.utils.upload_to_v2)),
            ],
            options={
                'verbose_name_plural': 'Forum - Blog Posts',
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='preview',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('AN', 'Announcement'), ('CH', 'Challenge'), ('BL', 'Blog_post')], default='AN', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='mextalki.blogpost'),
        ),
    ]
