from src.mextalki.models.available_lesson_time import *
from src.mextalki.models.carousel import *
from src.mextalki.models.common_video_score import *
from src.mextalki.models.conversation_club import *
from src.mextalki.models.copy_section import *
from src.mextalki.models.coupon import *
from src.mextalki.models.course import *
from src.mextalki.models.event import *
from src.mextalki.models.experience_points import *
from src.mextalki.models.faq import *
from src.mextalki.models.forum import *
from src.mextalki.models.leadership_score import *
from src.mextalki.models.lesson import *
from src.mextalki.models.lesson_activity import *
from src.mextalki.models.lesson_test import *
from src.mextalki.models.listening_practice import *
from src.mextalki.models.mask_info import *
from src.mextalki.models.module_info import *
from src.mextalki.models.paypal_payment import *
from src.mextalki.models.plan import *
from src.mextalki.models.plan_payment import *
from src.mextalki.models.podcast import *
from src.mextalki.models.podcast_test import *
from src.mextalki.models.referral import *
from src.mextalki.models.referral_credits import *
from src.mextalki.models.reminder import *
from src.mextalki.models.speaking_practice import *
from src.mextalki.models.stripe_payment import *
from src.mextalki.models.subscription import *
from src.mextalki.models.teacher import *
from src.mextalki.models.teachers_reviews import *
from src.mextalki.models.testimonials import *
from src.mextalki.models.used_coupons import *
from src.mextalki.models.useful_spanish import *
from src.mextalki.models.video import *
from src.mextalki.models.video_score import *
from src.mextalki.models.chat import *
