# Generated by Django 3.1.7 on 2021-03-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201111_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(
                default=False, help_text='Designates whether this user should be treated as verified with email.',
            ),
        ),
    ]
