# Generated by Django 3.1.7 on 2021-03-21 20:30

from django.db import migrations, models

import src.users.utils.upload_avatar


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True, null=True, upload_to=src.users.utils.upload_avatar.upload_avatar_to,
            ),
        ),
    ]
