from src.mextalki.views.announcement import *
from src.mextalki.views.buy_extra_hours import *
from src.mextalki.views.challenges import *
from src.mextalki.views.conversation_club import *
from src.mextalki.views.courses import *
from src.mextalki.views.handler_errors import *
from src.mextalki.views.index import *
from src.mextalki.views.leadership_board import *
from src.mextalki.views.lessons import *
from src.mextalki.views.password_reset import *
from src.mextalki.views.podcast import *
from src.mextalki.views.privacy_policy import privacy_policy, terms_of_use
from src.mextalki.views.process_payment import *
from src.mextalki.views.referral import *
from src.mextalki.views.stripe import *
from src.mextalki.views.swap_credits import *
from src.mextalki.views.videos import *
from src.mextalki.views.webhooks import *
from src.mextalki.views.forum import *
from src.mextalki.views.blog import *
