# Generated by Django 3.2.13 on 2022-05-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalPayment',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                (
                    'intent', models.CharField(
                        choices=[
                            ('CAPTURE', 'CAPTURE'), ('AUTHORIZE', 'AUTHORIZE'),
                        ], max_length=10,
                    ),
                ),
                (
                    'status', models.CharField(
                        choices=[
                            ('CREATED', 'CREATED'), ('SAVED', 'SAVED'), ('APPROVED', 'APPROVED'), (
                                'VOIDED', 'VOIDED',
                            ), ('COMPLETED', 'COMPLETED'), ('PAYER_ACTION_REQUIRED', 'PAYER_ACTION_REQUIRED'),
                        ], max_length=50,
                    ),
                ),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('payer_email', models.EmailField(max_length=254)),
                ('payer_id', models.CharField(max_length=20)),
                ('payer_name', models.CharField(max_length=300)),
            ],
        ),
    ]
