# Generated by Django 3.2.13 on 2022-05-20 02:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mextalki', '0064_alter_planpayment_user'),
        ('paypal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id', models.UUIDField(
                        default=uuid.uuid4,
                        editable=False, primary_key=True, serialize=False,
                    ),
                ),
                (
                    'paypal_payment', models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE, to='paypal.paypalpayment',
                    ),
                ),
                (
                    'plan', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='payment', to='mextalki.plan',
                    ),
                ),
                (
                    'user', models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='plan_payments', to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
