# Generated by Django 3.2.13 on 2022-05-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='referral_credits',
            field=models.IntegerField(
                default=0, help_text='earned credits when referral subscribe referrer'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='billing_cycle',
            field=models.CharField(choices=[('WEEK', 'WEEKLY'), ('MONTH', 'MONTHLY'), (
                'YEAR', 'YEARLY'), ('BIANNUALLY', 'BIANNUALLY')], default='MONTH', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='include_basic_package',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='include_conversation_club',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='include_podcast_features',
            field=models.BooleanField(default=True),
        ),
    ]
