# Generated by Django 3.2.13 on 2022-05-01 22:25

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20220501_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'ordering': ('-billing_cycle', 'price')},
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[
                                      django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='billing_cycle',
            field=models.CharField(choices=[(
                'MONTH', 'MONTHLY'), ('BIANNUALLY', 'BIANNUALLY')], default='MONTH', max_length=10),
        ),
    ]
