# Generated by Django 3.2.13 on 2022-05-02 00:47

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20220501_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='color',
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='best_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='billing_cycle',
            field=models.CharField(
                choices=[('MONTH', 'MONTHLY'), ('HALF YEAR', 'HALF YEAR')], default='MONTH', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(
                0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
